[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_event = 'InsertEnter'

[[plugins]]
repo = 'glepnir/spaceline.vim'
on_event = 'InsertEnter'
hook_source = 'source ~/.config/nvim/container/ftplugin/spaceline.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'
on_func = 'TableModeToggle'
hook_source = '''
nnoremap <LEADER>m :TableModeToggle<CR>
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_event = 'InsertEnter'
on_ft = 'snippet'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'skywind3000/asyncrun.extra'
on_event = ['BufRead', 'BufNewFile']
# hook_source = 'source ~/.config/nvim/container/ftplugin/asyncrun.vim'

# [[plugins]]
# repo = 'skywind3000/asynctasks.vim'
# on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'mg979/vim-visual-multi'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'preservim/nerdcommenter'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = ['BufRead', 'BufNewFile']
hook_source = 'source ~/.config/nvim/container/ftplugin/auto-pairs.vim'

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['BufRead', 'BufNewFile']

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
# hook_source = 'source ~/.config/nvim/container/ftplugin/go.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = 'python'

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
hook_source = 'source ~/.config/nvim/container/ftplugin/python.vim'

[[plugins]]
repo = 'demonlord1997/pycomment'
on_ft = 'python'
hook_source = 'source ~/.config/nvim/container/ftplugin/pycomment.vim'

[[plugins]]
repo = 'demonlord1997/markdown-org'
on_ft = 'markdown'
hook_source = """
source $HOME/.config/nvim/container/ftplugin/markdown.vim
"""

[[plugins]]
repo = 'voldikss/vim-translator'
on_event = ['BufRead', 'BufNewFile']
hook_source = 'source ~/.config/nvim/container/plugin/vim-translator.vim'
