[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'
on_event = 'BufRead,BufNewFile'
hook_add = 'source ~/.config/nvim/container/ftplugin/markdown.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
on_event = 'BufRead,BufNewFile'
hook_add = 'source ~/.config/nvim/container/ftplugin/ultisnips.vim'

[[plugins]]
repo = 'honza/vim-snippets'
on_source = 'ultisnips'


[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_event = 'BufRead,BufNewFile'

[[plugins]]
repo = 'preservim/nerdcommenter'
on_event = 'BufRead,BufNewFile'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'BufRead,BufNewFile'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'BufRead,BufNewFile'
hook_add = 'source ~/.config/nvim/container/ftplugin/auto-pairs.vim'

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = 'BufRead,BufNewFile'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = 'source ~/.config/nvim/container/ftplugin/go.vim'

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
hook_add = 'source ~/.config/nvim/container/ftplugin/python.vim'

[[plugins]]
repo = 'demonlord1997/pycomment'
on_ft = 'python'
hook_add = 'source ~/.config/nvim/container/ftplugin/pycomment.vim'
